coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        informational: true
        target: auto
        threshold: 5%

codecov:
  notify:
    after_n_builds: 3